### ISSUE TITLE
Combine scale and dims for retina images

### ISSUE THREAD

**Issue by vierkantemeter** [modxcms/Resizer#10]
I'm trying to use Resizer to create retina images with a max width or max height.

This is my code:

```
[[+tv.logo:pthumb=`h=60&w=120&f=jpg&q=75&qmax=90&scale=2&dims=1`]]
```

But this won't work: the dimensions that pthumb adds are not the given width / height (60 / 120) but the larger scaled ones (for example a height of 120). This way the image is displayed twice the size it should be.

I can't put the image width and height in myself, because it's a max width and height, so it's different for each image.

Am I doing something wrong or is it a bug?

(using MODX 2.3.3, Resizer 1.0.1, pThumb 2.3.3)

**Comment by oo12** [comment]
It's more of a limitation than a bug.  The first time through—when there's no cached thumbnail—it would be easy to output the unscaled dimensions instead of the actual ones, yes.  But all subsequent times these won't be readily available.  The scale isn't stored with the thumbnail, so Resizer would have to redo the whole calculation—every time—in order to figure it out.  It can't simply use the input value for scale since the scale could have been reduced if the original image wasn't big enough.
This would be detrimental to performance, and the width and height attributes on an img element aren't useful enough to justify that, I think.  Almost all of the time you can accomplish this with CSS.  You're very likely putting the images in some sort of grid anyway, so just set a max width or max height on the image or its container and let the other dimension be automatically scaled in proportion.  The images can have varying sizes and aspect ratios and you don't need to know what they are even; the browser will figure it out and fit them in.

**Comment by vierkantemeter** [comment]
Ok, thanks, I  understand. I'll use CSS instead :)
